const Database=require("better-sqlite3");const path=require("path");const fs=require("fs");let db;
const SCHEMA_VERSION=4;
function openLocalDatabase(userData){if(db)return db;fs.mkdirSync(userData,{recursive:true});const file=path.join(userData,"fh-traders.db");db=new Database(file);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");db.pragma("busy_timeout = 5000");migrate(db);return db}
function migrate(d){d.exec(`CREATE TABLE IF NOT EXISTS local_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS local_devices(device_key TEXT PRIMARY KEY,cloud_device_id TEXT,name TEXT,location_label TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sync_state(stream TEXT PRIMARY KEY,cursor INTEGER NOT NULL DEFAULT 0,last_synced_at TEXT,last_error TEXT);
CREATE TABLE IF NOT EXISTS sync_outbox(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,operation_type TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_sync_outbox_status ON sync_outbox(status,created_at);
CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,category_id TEXT,unit TEXT NOT NULL,sku TEXT,current_stock REAL NOT NULL DEFAULT 0,avg_cost REAL NOT NULL DEFAULT 0,default_purchase_price REAL NOT NULL DEFAULT 0,default_selling_price REAL NOT NULL DEFAULT 0,reorder_level REAL NOT NULL DEFAULT 0,max_stock_level REAL NOT NULL DEFAULT 0,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS restaurants(id TEXT PRIMARY KEY,name TEXT NOT NULL,contact_person TEXT,phone TEXT,address TEXT,email TEXT,credit_terms TEXT,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS suppliers(id TEXT PRIMARY KEY,name TEXT NOT NULL,contact_person TEXT,phone TEXT,email TEXT,address TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS vault_users(id TEXT PRIMARY KEY,name TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,vault_type TEXT);
CREATE TABLE IF NOT EXISTS pos_sales(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,cloud_id TEXT,invoice_no TEXT NOT NULL,cloud_invoice_no TEXT,created_at TEXT NOT NULL,customer_name TEXT,subtotal REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,grand_total REAL NOT NULL,payment_method TEXT NOT NULL,vault_user_id TEXT,cashier TEXT,sync_status TEXT NOT NULL DEFAULT 'pending',sync_error TEXT);
CREATE TABLE IF NOT EXISTS local_purchases(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,cloud_id TEXT,reference_no TEXT NOT NULL,cloud_reference_no TEXT,supplier_id TEXT,supplier_name TEXT,purchase_date TEXT NOT NULL,grand_total REAL NOT NULL,notes TEXT,amount_paid REAL NOT NULL DEFAULT 0,sync_status TEXT NOT NULL DEFAULT 'pending',sync_error TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS local_purchase_items(id TEXT PRIMARY KEY,purchase_id TEXT NOT NULL REFERENCES local_purchases(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,unit TEXT NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,line_total REAL NOT NULL);
CREATE TABLE IF NOT EXISTS local_purchase_payments(id TEXT PRIMARY KEY,purchase_id TEXT NOT NULL REFERENCES local_purchases(id) ON DELETE CASCADE,vault_user_id TEXT NOT NULL,amount REAL NOT NULL,method TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS local_sales(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,cloud_id TEXT,invoice_no TEXT NOT NULL,cloud_invoice_no TEXT,restaurant_id TEXT NOT NULL,restaurant_name TEXT NOT NULL,sale_date TEXT NOT NULL,subtotal REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,tax REAL NOT NULL DEFAULT 0,grand_total REAL NOT NULL,amount_received REAL NOT NULL DEFAULT 0,notes TEXT,sync_status TEXT NOT NULL DEFAULT 'pending',sync_error TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS local_sale_items(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES local_sales(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,unit TEXT NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,cost_price REAL NOT NULL,line_total REAL NOT NULL);
CREATE TABLE IF NOT EXISTS local_sale_payments(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES local_sales(id) ON DELETE CASCADE,vault_user_id TEXT NOT NULL,amount REAL NOT NULL,method TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pos_sale_items(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES pos_sales(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,unit TEXT NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,line_total REAL NOT NULL);
`);d.prepare("INSERT INTO local_meta(key,value) VALUES('schema_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(String(SCHEMA_VERSION));}
const ALLOWED={vault_users:["id","name","is_active","vault_type"],categories:["id","name","color","created_at","updated_at"],products:["id","name","category_id","unit","sku","current_stock","avg_cost","default_purchase_price","default_selling_price","reorder_level","max_stock_level","created_at","updated_at"],restaurants:["id","name","contact_person","phone","address","email","credit_terms","is_active","created_at","updated_at"],suppliers:["id","name","contact_person","phone","email","address","created_at","updated_at"]};
function bootstrap(d,payload){const tx=d.transaction(()=>{let total=0;for(const [table,cols] of Object.entries(ALLOWED)){const rows=Array.isArray(payload?.[table])?payload[table]:[];if(!rows.length)continue;const qs=cols.map(()=>"?").join(",");const updates=cols.filter(c=>c!=="id").map(c=>`${c}=excluded.${c}`).join(",");const stmt=d.prepare(`INSERT INTO ${table}(${cols.join(",")}) VALUES(${qs}) ON CONFLICT(id) DO UPDATE SET ${updates}`);for(const row of rows){stmt.run(...cols.map(c=>c==="is_active"?(row[c]===false?0:1):(row[c]??null)));total++}}d.prepare("INSERT INTO local_meta(key,value) VALUES('last_bootstrap_at',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(new Date().toISOString());return total});return tx()}
function getDevice(d,name){let row=d.prepare("SELECT * FROM local_devices LIMIT 1").get();if(!row){const key=require("crypto").randomUUID();d.prepare("INSERT INTO local_devices(device_key,name) VALUES(?,?)").run(key,name||"FH Traders Desktop");row=d.prepare("SELECT * FROM local_devices WHERE device_key=?").get(key)}return row}
function setCloudDeviceId(d,key,id){d.prepare("UPDATE local_devices SET cloud_device_id=?,updated_at=CURRENT_TIMESTAMP WHERE device_key=?").run(id,key)}
function listPosData(d){return {products:d.prepare("SELECT id,name,sku,unit,current_stock,default_selling_price,category_id FROM products ORDER BY name").all(),categories:d.prepare("SELECT id,name FROM categories ORDER BY name").all(),vaults:d.prepare("SELECT id,name FROM vault_users WHERE is_active=1 AND vault_type='business_cash' ORDER BY name").all()}}
function createLocalPosSale(d,input){const tx=d.transaction(()=>{const id=input.id,op=input.operation_id,now=new Date().toISOString();let sub=0;for(const item of input.items){const p=d.prepare("SELECT * FROM products WHERE id=?").get(item.product_id);if(!p)throw new Error("Product not available locally");if(Number(item.quantity)<=0||Number(item.quantity)>Number(p.current_stock))throw new Error(`Insufficient local stock for ${p.name}`);if(Number(item.unit_price)<0)throw new Error("Invalid price");sub+=Number(item.quantity)*Number(item.unit_price)}const disc=Number(input.discount||0);if(disc<0||disc>sub)throw new Error("Invalid discount");const grand=sub-disc;const invoice=`OFF-${now.slice(2,10).replace(/-/g,"")}-${id.slice(0,6).toUpperCase()}`;d.prepare("INSERT INTO pos_sales(id,operation_id,invoice_no,created_at,customer_name,subtotal,discount,grand_total,payment_method,vault_user_id,cashier) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(id,op,invoice,now,input.customer_name||null,sub,disc,grand,input.payment_method,input.vault_user_id||null,input.cashier||"-");for(const item of input.items){const p=d.prepare("SELECT name,unit FROM products WHERE id=?").get(item.product_id);const line=Number(item.quantity)*Number(item.unit_price);d.prepare("INSERT INTO pos_sale_items(id,sale_id,product_id,name,unit,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?)").run(require("crypto").randomUUID(),id,item.product_id,p.name,p.unit,item.quantity,item.unit_price,line);d.prepare("UPDATE products SET current_stock=current_stock-? WHERE id=?").run(item.quantity,item.product_id)}d.prepare("INSERT INTO sync_outbox(id,entity_type,entity_id,operation_type,payload) VALUES(?,?,?,?,?)").run(op,"sales",id,"insert",JSON.stringify({...input,local_sale_id:id}));return getLocalReceipt(d,id)});return tx()}
function listPurchaseData(d){return {products:d.prepare("SELECT id,name,sku,unit,current_stock,avg_cost,default_purchase_price,category_id FROM products ORDER BY name").all(),suppliers:d.prepare("SELECT id,name FROM suppliers ORDER BY name").all(),vaults:d.prepare("SELECT id,name FROM vault_users WHERE is_active=1 AND vault_type='business_cash' ORDER BY name").all()}}
function createLocalPurchase(d,input){const tx=d.transaction(()=>{const id=input.id,op=input.operation_id,now=new Date().toISOString();if(!input.supplier_id&&!String(input.new_supplier_name||"").trim())throw new Error("Supplier is required");if(!input.purchase_date)throw new Error("Purchase date is required");if(!Array.isArray(input.items)||!input.items.length)throw new Error("Add at least one product");let total=0;for(const item of input.items){const p=d.prepare("SELECT * FROM products WHERE id=?").get(item.product_id);if(!p)throw new Error("Product not available locally");if(Number(item.quantity)<=0||Number(item.unit_price)<=0)throw new Error("Quantity and unit price must be greater than zero");total+=Number(item.quantity)*Number(item.unit_price)}const payments=(input.payments||[]).filter(x=>Number(x.amount)>0);const paid=payments.reduce((n,x)=>n+Number(x.amount),0);if(paid>total+.001)throw new Error("Paid amount cannot exceed the grand total");if(payments.some(x=>!x.vault_user_id||!x.method))throw new Error("Every payment requires a Vault User and method");const supplier=input.supplier_id?d.prepare("SELECT name FROM suppliers WHERE id=?").get(input.supplier_id):null;const ref=`OFF-PUR-${now.slice(2,10).replace(/-/g,"")}-${id.slice(0,6).toUpperCase()}`;d.prepare("INSERT INTO local_purchases(id,operation_id,reference_no,supplier_id,supplier_name,purchase_date,grand_total,notes,amount_paid,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,op,ref,input.supplier_id||null,supplier?.name||String(input.new_supplier_name||"").trim(),input.purchase_date,total,input.notes||null,paid,now);for(const item of input.items){const p=d.prepare("SELECT name,unit,current_stock,avg_cost FROM products WHERE id=?").get(item.product_id);const qty=Number(item.quantity),price=Number(item.unit_price),newStock=Number(p.current_stock)+qty,newAvg=newStock>0?((Number(p.current_stock)*Number(p.avg_cost))+(qty*price))/newStock:Number(p.avg_cost);d.prepare("INSERT INTO local_purchase_items(id,purchase_id,product_id,name,unit,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?)").run(require("crypto").randomUUID(),id,item.product_id,p.name,p.unit,qty,price,qty*price);d.prepare("UPDATE products SET current_stock=?,avg_cost=? WHERE id=?").run(newStock,newAvg,item.product_id)}for(const x of payments)d.prepare("INSERT INTO local_purchase_payments(id,purchase_id,vault_user_id,amount,method) VALUES(?,?,?,?,?)").run(require("crypto").randomUUID(),id,x.vault_user_id,Number(x.amount),x.method);d.prepare("INSERT INTO sync_outbox(id,entity_type,entity_id,operation_type,payload) VALUES(?,?,?,?,?)").run(op,"purchases",id,"insert",JSON.stringify({...input,local_purchase_id:id}));return d.prepare("SELECT * FROM local_purchases WHERE id=?").get(id)});return tx()}
function listLocalPurchases(d){return d.prepare("SELECT * FROM local_purchases ORDER BY purchase_date DESC,created_at DESC LIMIT 250").all().map(p=>({...p,suppliers:{name:p.supplier_name},purchase_items:d.prepare('SELECT id,product_id,quantity,unit_price,line_total,name,unit FROM local_purchase_items WHERE purchase_id=?').all(p.id).map(x=>({...x,products:{name:x.name,unit:x.unit}})),payment_status:p.amount_paid>=p.grand_total-.001?'paid':p.amount_paid>0?'partial':'unpaid',is_local:true}))}
function pendingPurchases(d){return d.prepare("SELECT * FROM sync_outbox WHERE status IN ('pending','failed') AND entity_type='purchases' ORDER BY created_at").all().map(x=>({...x,payload:JSON.parse(x.payload)}))}
function markPurchaseSynced(d,op,cloud){const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(!row)return;d.transaction(()=>{d.prepare("UPDATE sync_outbox SET status='synced',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(op);d.prepare("UPDATE local_purchases SET sync_status='synced',cloud_id=?,cloud_reference_no=?,sync_error=NULL WHERE id=?").run(cloud.id,cloud.reference_no,row.entity_id)})()}
function markPurchaseFailed(d,op,error){d.prepare("UPDATE sync_outbox SET status='failed',attempts=attempts+1,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(error),op);const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(row)d.prepare("UPDATE local_purchases SET sync_status='failed',sync_error=? WHERE id=?").run(String(error),row.entity_id)}
function listNormalSaleData(d){return {products:d.prepare("SELECT id,name,sku,unit,current_stock,avg_cost,category_id FROM products ORDER BY name").all(),restaurants:d.prepare("SELECT id,name FROM restaurants WHERE is_active=1 ORDER BY name").all(),vaults:d.prepare("SELECT id,name FROM vault_users WHERE is_active=1 AND vault_type='business_cash' ORDER BY name").all()}}
function createLocalNormalSale(d,input){const tx=d.transaction(()=>{const id=input.id,op=input.operation_id,now=new Date().toISOString();const rest=d.prepare("SELECT name FROM restaurants WHERE id=? AND is_active=1").get(input.restaurant_id);if(!rest)throw new Error("Restaurant is not available locally");if(!input.sale_date)throw new Error("Sale date is required");if(!Array.isArray(input.items)||!input.items.length)throw new Error("Add at least one product");let sub=0;for(const item of input.items){const p=d.prepare("SELECT * FROM products WHERE id=?").get(item.product_id);if(!p)throw new Error("Product not available locally");const qty=Number(item.quantity),price=Number(item.unit_price);if(qty<=0||qty>Number(p.current_stock))throw new Error(`Insufficient local stock for ${p.name}`);if(price<=0)throw new Error("Selling price must be greater than zero");if(Number(p.avg_cost)>0&&price<Number(p.avg_cost))throw new Error(`Selling price cannot be lower than cost for ${p.name}`);sub+=qty*price}const discount=Number(input.discount||0),tax=Number(input.tax||0),grand=Math.max(0,sub-discount+tax),received=Number(input.received||0);if(discount<0||discount>sub)throw new Error("Invalid discount");if(received<0||received>grand)throw new Error("Initial Payment cannot exceed the Grand Total");if(received>0&&(!input.payment_method||!input.vault_user_id))throw new Error("Payment method and Business Cash Vault are required");const invoice=`OFF-SAL-${now.slice(2,10).replace(/-/g,"")}-${id.slice(0,6).toUpperCase()}`;d.prepare("INSERT INTO local_sales(id,operation_id,invoice_no,restaurant_id,restaurant_name,sale_date,subtotal,discount,tax,grand_total,amount_received,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,op,invoice,input.restaurant_id,rest.name,input.sale_date,sub,discount,tax,grand,received,input.notes||null,now);for(const item of input.items){const p=d.prepare("SELECT name,unit,avg_cost FROM products WHERE id=?").get(item.product_id),qty=Number(item.quantity),price=Number(item.unit_price);d.prepare("INSERT INTO local_sale_items(id,sale_id,product_id,name,unit,quantity,unit_price,cost_price,line_total) VALUES(?,?,?,?,?,?,?,?,?)").run(require("crypto").randomUUID(),id,item.product_id,p.name,p.unit,qty,price,Number(p.avg_cost),qty*price);d.prepare("UPDATE products SET current_stock=current_stock-? WHERE id=?").run(qty,item.product_id)}if(received>0)d.prepare("INSERT INTO local_sale_payments(id,sale_id,vault_user_id,amount,method) VALUES(?,?,?,?,?)").run(require("crypto").randomUUID(),id,input.vault_user_id,received,input.payment_method);d.prepare("INSERT INTO sync_outbox(id,entity_type,entity_id,operation_type,payload) VALUES(?,?,?,?,?)").run(op,"normal_sales",id,"insert",JSON.stringify({...input,local_sale_id:id}));return d.prepare("SELECT * FROM local_sales WHERE id=?").get(id)});return tx()}
function listLocalNormalSales(d){return d.prepare("SELECT * FROM local_sales ORDER BY sale_date DESC,created_at DESC LIMIT 250").all().map(s=>({...s,restaurants:{name:s.restaurant_name},sale_items:d.prepare("SELECT id,product_id,quantity,unit_price,line_total,name,unit FROM local_sale_items WHERE sale_id=?").all(s.id).map(x=>({...x,products:{name:x.name,unit:x.unit}})),payment_status:s.amount_received>=s.grand_total-.001?'paid':s.amount_received>0?'partial':'unpaid',is_local:true}))}
function pendingNormalSales(d){return d.prepare("SELECT * FROM sync_outbox WHERE status IN ('pending','failed') AND entity_type='normal_sales' ORDER BY created_at").all().map(x=>({...x,payload:JSON.parse(x.payload)}))}
function markNormalSaleSynced(d,op,cloud){const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(!row)return;d.transaction(()=>{d.prepare("UPDATE sync_outbox SET status='synced',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(op);d.prepare("UPDATE local_sales SET sync_status='synced',cloud_id=?,cloud_invoice_no=?,sync_error=NULL WHERE id=?").run(cloud.id,cloud.invoice_no,row.entity_id)})()}
function markNormalSaleFailed(d,op,error){d.prepare("UPDATE sync_outbox SET status='failed',attempts=attempts+1,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(error),op);const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(row)d.prepare("UPDATE local_sales SET sync_status='failed',sync_error=? WHERE id=?").run(String(error),row.entity_id)}
function getLocalReceipt(d,id){const s=d.prepare("SELECT * FROM pos_sales WHERE id=?").get(id);if(!s)return null;const items=d.prepare("SELECT quantity,unit_price,line_total,name,unit FROM pos_sale_items WHERE sale_id=?").all(id).map(x=>({...x,products:{name:x.name,unit:x.unit}}));return {...s,sale_items:items,amount_received:s.grand_total}}
function syncCenter(d){return d.prepare(`SELECT o.id,o.entity_type,o.entity_id,o.operation_type,o.status,o.attempts,o.last_error,o.created_at,o.updated_at,COALESCE(s.invoice_no,p.reference_no,n.invoice_no) invoice_no,COALESCE(s.cloud_invoice_no,p.cloud_reference_no,n.cloud_invoice_no) cloud_invoice_no,COALESCE(s.grand_total,p.grand_total,n.grand_total) grand_total,COALESCE(s.customer_name,p.supplier_name,n.restaurant_name) customer_name FROM sync_outbox o LEFT JOIN pos_sales s ON s.id=o.entity_id AND o.entity_type='sales' LEFT JOIN local_purchases p ON p.id=o.entity_id AND o.entity_type='purchases' LEFT JOIN local_sales n ON n.id=o.entity_id AND o.entity_type='normal_sales' ORDER BY CASE o.status WHEN 'failed' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END,o.created_at DESC LIMIT 250`).all()}
function syncSummary(d){const rows=d.prepare("SELECT status,count(*) count FROM sync_outbox GROUP BY status").all();const counts={pending:0,failed:0,synced:0};for(const r of rows)counts[r.status]=r.count;return {...counts,total:rows.reduce((n,r)=>n+r.count,0)}}
function retrySync(d,id){d.prepare("UPDATE sync_outbox SET status='pending',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='failed'").run(id);d.prepare("UPDATE pos_sales SET sync_status='pending',sync_error=NULL WHERE operation_id=?").run(id);d.prepare("UPDATE local_purchases SET sync_status='pending',sync_error=NULL WHERE operation_id=?").run(id);d.prepare("UPDATE local_sales SET sync_status='pending',sync_error=NULL WHERE operation_id=?").run(id)}
function pendingPos(d){return d.prepare("SELECT * FROM sync_outbox WHERE status IN ('pending','failed') AND entity_type='sales' ORDER BY created_at").all().map(x=>({...x,payload:JSON.parse(x.payload)}))}
function markPosSynced(d,op,cloud){const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(!row)return;d.transaction(()=>{d.prepare("UPDATE sync_outbox SET status='synced',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(op);d.prepare("UPDATE pos_sales SET sync_status='synced',cloud_id=?,cloud_invoice_no=?,sync_error=NULL WHERE id=?").run(cloud.id,cloud.invoice_no,row.entity_id)})()}
function markPosFailed(d,op,error){d.prepare("UPDATE sync_outbox SET status='failed',attempts=attempts+1,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(error),op);const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(row)d.prepare("UPDATE pos_sales SET sync_status='failed',sync_error=? WHERE id=?").run(String(error),row.entity_id)}
function status(d){const counts={};for(const t of Object.keys(ALLOWED))counts[t]=d.prepare(`SELECT count(*) c FROM ${t}`).get().c;const meta=Object.fromEntries(d.prepare("SELECT key,value FROM local_meta").all().map(r=>[r.key,r.value]));return {schemaVersion:SCHEMA_VERSION,counts,meta,pendingOutbox:d.prepare("SELECT count(*) c FROM sync_outbox WHERE status='pending'").get().c}}
module.exports={openLocalDatabase,bootstrap,status,getDevice,setCloudDeviceId,listPosData,createLocalPosSale,getLocalReceipt,listPurchaseData,createLocalPurchase,listLocalPurchases,pendingPurchases,markPurchaseSynced,markPurchaseFailed,listNormalSaleData,createLocalNormalSale,listLocalNormalSales,pendingNormalSales,markNormalSaleSynced,markNormalSaleFailed,syncCenter,syncSummary,retrySync,pendingPos,markPosSynced,markPosFailed};