const Database=require("better-sqlite3");const path=require("path");const fs=require("fs");let db;
const SCHEMA_VERSION=2;
function openLocalDatabase(userData){if(db)return db;fs.mkdirSync(userData,{recursive:true});const file=path.join(userData,"fh-traders.db");db=new Database(file);db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");db.pragma("busy_timeout = 5000");migrate(db);return db}
function migrate(d){d.exec(`CREATE TABLE IF NOT EXISTS local_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS local_devices(device_key TEXT PRIMARY KEY,cloud_device_id TEXT,name TEXT,location_label TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sync_state(stream TEXT PRIMARY KEY,cursor INTEGER NOT NULL DEFAULT 0,last_synced_at TEXT,last_error TEXT);
CREATE TABLE IF NOT EXISTS sync_outbox(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,operation_type TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_sync_outbox_status ON sync_outbox(status,created_at);
CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,category_id TEXT,unit TEXT NOT NULL,sku TEXT,current_stock REAL NOT NULL DEFAULT 0,avg_cost REAL NOT NULL DEFAULT 0,default_purchase_price REAL NOT NULL DEFAULT 0,default_selling_price REAL NOT NULL DEFAULT 0,reorder_level REAL NOT NULL DEFAULT 0,max_stock_level REAL NOT NULL DEFAULT 0,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS restaurants(id TEXT PRIMARY KEY,name TEXT NOT NULL,contact_person TEXT,phone TEXT,address TEXT,email TEXT,credit_terms TEXT,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS suppliers(id TEXT PRIMARY KEY,name TEXT NOT NULL,contact_person TEXT,phone TEXT,email TEXT,address TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS vault_users(id TEXT PRIMARY KEY,name TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,vault_type TEXT);
CREATE TABLE IF NOT EXISTS pos_sales(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL UNIQUE,cloud_id TEXT,invoice_no TEXT NOT NULL,cloud_invoice_no TEXT,created_at TEXT NOT NULL,customer_name TEXT,subtotal REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,grand_total REAL NOT NULL,payment_method TEXT NOT NULL,vault_user_id TEXT,cashier TEXT,sync_status TEXT NOT NULL DEFAULT 'pending',sync_error TEXT);
CREATE TABLE IF NOT EXISTS pos_sale_items(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES pos_sales(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,unit TEXT NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,line_total REAL NOT NULL);
`);d.prepare("INSERT INTO local_meta(key,value) VALUES('schema_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(String(SCHEMA_VERSION));}
const ALLOWED={vault_users:["id","name","is_active","vault_type"],categories:["id","name","color","created_at","updated_at"],products:["id","name","category_id","unit","sku","current_stock","avg_cost","default_purchase_price","default_selling_price","reorder_level","max_stock_level","created_at","updated_at"],restaurants:["id","name","contact_person","phone","address","email","credit_terms","is_active","created_at","updated_at"],suppliers:["id","name","contact_person","phone","email","address","created_at","updated_at"]};
function bootstrap(d,payload){const tx=d.transaction(()=>{let total=0;for(const [table,cols] of Object.entries(ALLOWED)){const rows=Array.isArray(payload?.[table])?payload[table]:[];if(!rows.length)continue;const qs=cols.map(()=>"?").join(",");const updates=cols.filter(c=>c!=="id").map(c=>`${c}=excluded.${c}`).join(",");const stmt=d.prepare(`INSERT INTO ${table}(${cols.join(",")}) VALUES(${qs}) ON CONFLICT(id) DO UPDATE SET ${updates}`);for(const row of rows){stmt.run(...cols.map(c=>c==="is_active"?(row[c]===false?0:1):(row[c]??null)));total++}}d.prepare("INSERT INTO local_meta(key,value) VALUES('last_bootstrap_at',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(new Date().toISOString());return total});return tx()}
function listPosData(d){return {products:d.prepare("SELECT id,name,sku,unit,current_stock,default_selling_price,category_id FROM products ORDER BY name").all(),categories:d.prepare("SELECT id,name FROM categories ORDER BY name").all(),vaults:d.prepare("SELECT id,name FROM vault_users WHERE is_active=1 AND vault_type='business_cash' ORDER BY name").all()}}
function createLocalPosSale(d,input){const tx=d.transaction(()=>{const id=input.id,op=input.operation_id,now=new Date().toISOString();let sub=0;for(const item of input.items){const p=d.prepare("SELECT * FROM products WHERE id=?").get(item.product_id);if(!p)throw new Error("Product not available locally");if(Number(item.quantity)<=0||Number(item.quantity)>Number(p.current_stock))throw new Error(`Insufficient local stock for ${p.name}`);if(Number(item.unit_price)<0)throw new Error("Invalid price");sub+=Number(item.quantity)*Number(item.unit_price)}const disc=Number(input.discount||0);if(disc<0||disc>sub)throw new Error("Invalid discount");const grand=sub-disc;const invoice=`OFF-${now.slice(2,10).replace(/-/g,"")}-${id.slice(0,6).toUpperCase()}`;d.prepare("INSERT INTO pos_sales(id,operation_id,invoice_no,created_at,customer_name,subtotal,discount,grand_total,payment_method,vault_user_id,cashier) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(id,op,invoice,now,input.customer_name||null,sub,disc,grand,input.payment_method,input.vault_user_id||null,input.cashier||"-");for(const item of input.items){const p=d.prepare("SELECT name,unit FROM products WHERE id=?").get(item.product_id);const line=Number(item.quantity)*Number(item.unit_price);d.prepare("INSERT INTO pos_sale_items(id,sale_id,product_id,name,unit,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?)").run(require("crypto").randomUUID(),id,item.product_id,p.name,p.unit,item.quantity,item.unit_price,line);d.prepare("UPDATE products SET current_stock=current_stock-? WHERE id=?").run(item.quantity,item.product_id)}d.prepare("INSERT INTO sync_outbox(id,entity_type,entity_id,operation_type,payload) VALUES(?,?,?,?,?)").run(op,"sales",id,"insert",JSON.stringify({...input,local_sale_id:id}));return getLocalReceipt(d,id)});return tx()}
function getLocalReceipt(d,id){const s=d.prepare("SELECT * FROM pos_sales WHERE id=?").get(id);if(!s)return null;const items=d.prepare("SELECT quantity,unit_price,line_total,name,unit FROM pos_sale_items WHERE sale_id=?").all(id).map(x=>({...x,products:{name:x.name,unit:x.unit}}));return {...s,sale_items:items,amount_received:s.grand_total}}
function pendingPos(d){return d.prepare("SELECT * FROM sync_outbox WHERE status IN ('pending','failed') AND entity_type='sales' ORDER BY created_at").all().map(x=>({...x,payload:JSON.parse(x.payload)}))}
function markPosSynced(d,op,cloud){const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(!row)return;d.transaction(()=>{d.prepare("UPDATE sync_outbox SET status='synced',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(op);d.prepare("UPDATE pos_sales SET sync_status='synced',cloud_id=?,cloud_invoice_no=?,sync_error=NULL WHERE id=?").run(cloud.id,cloud.invoice_no,row.entity_id)})()}
function markPosFailed(d,op,error){d.prepare("UPDATE sync_outbox SET status='failed',attempts=attempts+1,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(error),op);const row=d.prepare("SELECT entity_id FROM sync_outbox WHERE id=?").get(op);if(row)d.prepare("UPDATE pos_sales SET sync_status='failed',sync_error=? WHERE id=?").run(String(error),row.entity_id)}
function status(d){const counts={};for(const t of Object.keys(ALLOWED))counts[t]=d.prepare(`SELECT count(*) c FROM ${t}`).get().c;const meta=Object.fromEntries(d.prepare("SELECT key,value FROM local_meta").all().map(r=>[r.key,r.value]));return {schemaVersion:SCHEMA_VERSION,counts,meta,pendingOutbox:d.prepare("SELECT count(*) c FROM sync_outbox WHERE status='pending'").get().c}}
module.exports={openLocalDatabase,bootstrap,status,listPosData,createLocalPosSale,getLocalReceipt,pendingPos,markPosSynced,markPosFailed};