const {openLocalDatabase,bootstrap:bootstrapLocal,status:localStatus,listPosData,createLocalPosSale,getLocalReceipt,pendingPos,markPosSynced,markPosFailed,getDevice,setCloudDeviceId,syncCenter,syncSummary,retrySync}=require("./local-db.cjs");
const {app,BrowserWindow,ipcMain,shell}=require("electron");const path=require("path");const fs=require("fs");const {spawn}=require("child_process");
const isDev=!app.isPackaged;let localServer=null;const LOCAL_PORT=32145;
function startBundledServer(){if(isDev)return Promise.resolve();const entry=path.join(process.resourcesPath,"app.asar.unpacked",".output","server","index.mjs");if(!fs.existsSync(entry))throw new Error("Bundled application server is missing");localServer=spawn(process.execPath,[entry],{env:{...process.env,ELECTRON_RUN_AS_NODE:"1",PORT:String(LOCAL_PORT),HOST:"127.0.0.1"},stdio:"ignore",windowsHide:true});return new Promise((resolve,reject)=>{const started=Date.now();const check=()=>{require("http").get(`http://127.0.0.1:${LOCAL_PORT}`,r=>{r.resume();resolve()}).on("error",()=>{if(Date.now()-started>15000)reject(new Error("Local application server did not start"));else setTimeout(check,150)});check()})}
function state(){const dir=app.getPath("userData");fs.mkdirSync(dir,{recursive:true});return {platform:process.platform,version:app.getVersion(),dataDirectory:dir,isPackaged:app.isPackaged};}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,show:false,backgroundColor:"#ffffff",webPreferences:{preload:path.join(__dirname,"preload.cjs"),contextIsolation:true,nodeIntegration:false,sandbox:true}});
win.once("ready-to-show",()=>win.show());win.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/.test(url)){shell.openExternal(url);return {action:"deny"}}return {action:"allow"}});
if(isDev){win.loadURL(process.env.FH_DESKTOP_DEV_URL||"http://localhost:5173");}else{win.loadURL(`http://127.0.0.1:${LOCAL_PORT}`);}}
app.whenReady().then(async()=>{await startBundledServer();const localDb=openLocalDatabase(app.getPath("userData"));ipcMain.handle("desktop:get-state",()=>state());ipcMain.handle("desktop:get-storage-path",()=>app.getPath("userData"));ipcMain.handle("local-db:status",()=>localStatus(localDb));ipcMain.handle("local-db:bootstrap",(_event,payload)=>({imported:bootstrapLocal(localDb,payload),...localStatus(localDb)}));ipcMain.handle("desktop:device",()=>getDevice(localDb,require("os").hostname()));ipcMain.handle("desktop:set-cloud-device",(_e,{key,id})=>setCloudDeviceId(localDb,key,id));ipcMain.handle("pos:local-data",()=>listPosData(localDb));ipcMain.handle("pos:create-local",(_e,payload)=>createLocalPosSale(localDb,payload));ipcMain.handle("pos:receipt",(_e,id)=>getLocalReceipt(localDb,id));ipcMain.handle("sync:center",()=>syncCenter(localDb));ipcMain.handle("sync:summary",()=>syncSummary(localDb));ipcMain.handle("sync:retry",(_e,id)=>retrySync(localDb,id));ipcMain.handle("pos:pending",()=>pendingPos(localDb));ipcMain.handle("pos:mark-synced",(_e,{operationId,cloud})=>markPosSynced(localDb,operationId,cloud));ipcMain.handle("pos:mark-failed",(_e,{operationId,error})=>markPosFailed(localDb,operationId,error));createWindow();app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});
app.on("before-quit",()=>{if(localServer) localServer.kill()});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});