import {useEffect,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {supabase} from "@/integrations/supabase/client";import {toast} from "sonner";import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";import {Button} from "@/components/ui/button";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
export function PosAdjustmentDialog({open,onOpenChange,sale,mode}:{open:boolean;onOpenChange:(v:boolean)=>void;sale:any;mode:"item_less"|"delete"|"edit"}){
 const qc=useQueryClient(),[product,setProduct]=useState(""),[qty,setQty]=useState(1),[reason,setReason]=useState(""),[password,setPassword]=useState("");
 const [items,setItems]=useState<any[]>([]);
 const [customer,setCustomer]=useState("");
 const [discount,setDiscount]=useState(0);
 const [initialized,setInitialized]=useState(false);
 useEffect(()=>{if(open&&sale&&!initialized){setItems((sale.sale_items??[]).map((i:any)=>({product_id:i.product_id,quantity:Number(i.quantity),unit_price:Number(i.unit_price),name:i.products?.name??"Item"})));setCustomer(sale.customer_name??"");setDiscount(Number(sale.discount??0));setInitialized(true);}},[open,sale,initialized]);
 const save=useMutation({mutationFn:async()=>{if(!reason.trim()||!password)throw new Error("Reason and authorization password are required");if(mode==="edit"&&(!items.length||items.some(i=>i.quantity<=0||i.unit_price<0)))throw new Error("Invoice must contain valid items");
 const {error}=mode==="edit"?await (supabase.rpc as any)("pos_edit_sale",{p_sale_id:sale.id,p_items:items.map(({product_id,quantity,unit_price})=>({product_id,quantity,unit_price})),p_customer_name:customer,p_discount:discount,p_reason:reason,p_password:password}):mode==="delete"?await (supabase.rpc as any)("void_pos_sale",{p_sale_id:sale.id,p_reason:reason,p_password:password}):await (supabase.rpc as any)("pos_item_less",{p_sale_id:sale.id,p_product_id:product,p_quantity:qty,p_reason:reason,p_password:password});if(error)throw error},onSuccess:()=>{toast.success(mode==="delete"?"POS sale deleted and audited":mode==="edit"?"Invoice updated":"POS item less recorded");qc.invalidateQueries();onOpenChange(false)},onError:(e:Error)=>toast.error(e.message)});
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{mode==="delete"?"Delete POS Sale":mode==="edit"?"Edit POS Invoice":"Item Less"} · {sale?.invoice_no}</DialogTitle></DialogHeader><div className="space-y-3">
 {mode==="edit"&&<div className="space-y-2"><Label>Invoice items</Label>{items.map((i,index)=><div key={i.product_id} className="grid grid-cols-[1fr_85px_105px] gap-2 items-center"><span className="text-sm">{i.name}</span><Input aria-label="Quantity" type="number" min="0.001" step="any" value={i.quantity} onChange={e=>setItems(a=>a.map((x,j)=>j===index?{...x,quantity:Number(e.target.value)}:x))}/><Input aria-label="Unit price" type="number" min="0" step="any" value={i.unit_price} onChange={e=>setItems(a=>a.map((x,j)=>j===index?{...x,unit_price:Number(e.target.value)}:x))}/></div>)}<Label>Customer</Label><Input value={customer} onChange={e=>setCustomer(e.target.value)}/><Label>Discount</Label><Input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></div>}
 {mode==="item_less"&&<><div><Label>Item</Label><Select value={product} onValueChange={setProduct}><SelectTrigger><SelectValue placeholder="Select item"/></SelectTrigger><SelectContent>{(sale?.sale_items??[]).map((i:any)=><SelectItem key={i.product_id} value={i.product_id}>{i.products?.name} · Qty {i.quantity}</SelectItem>)}</SelectContent></Select></div><div><Label>Quantity to remove</Label><Input type="number" min={0.001} value={qty} onChange={e=>setQty(Number(e.target.value))}/></div></>}
 <div><Label>Reason</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required audit reason"/></div><div><Label>Authorization Password</Label><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password configured in Admin Settings"/></div>
 <Button variant={mode==="delete"?"destructive":"default"} className="w-full" onClick={()=>save.mutate()} disabled={save.isPending|| (mode==="item_less"&&!product)}>{mode==="delete"?"Delete & Restore Stock":mode==="edit"?"Save Authorized Changes":"Apply Item Less"}</Button></div></DialogContent></Dialog>
}