import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { BarChart, Bar, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FileSpreadsheet, Printer } from "lucide-react";
import { PageHeader } from "@/components/app/PageHeader";
import { RangePicker } from "@/components/app/RangePicker";
import { useAuth } from "@/hooks/useAuth";
import { useAnalytics, useDateRange } from "@/lib/useAnalytics";
import { formatCurrency, formatDate } from "@/lib/format";
import { printReport } from "@/lib/print";
import { downloadExcel } from "@/lib/xlsx";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export const Route = createFileRoute("/_authenticated/reports")({ component: ReportsPage });
const COLORS = ["var(--chart-1)", "var(--chart-2)", "var(--chart-3)", "var(--chart-4)"];
const status = (outstanding: number) => outstanding <= 0.001 ? "Paid" : "Outstanding";
const pct = (value: number) => `${value.toFixed(1)}%`;

function ReportsPage() {
  const { isAdmin, loading } = useAuth();
  const navigate = useNavigate();
  const { preset, setPreset, custom, setCustom, range } = useDateRange("month");
  const a = useAnalytics(range.from, range.to);
  useEffect(() => { if (!loading && !isAdmin) navigate({ to: "/dashboard", replace: true }); }, [loading, isAdmin, navigate]);
  if (!isAdmin) return null;
  const period = `${formatDate(range.from)} – ${formatDate(range.to)}`;
  const netMargin = a.totalSales ? a.netProfit / a.totalSales * 100 : 0;
  const grossAssets = a.currentCashOnHand + a.outstanding + a.inventoryAtCost;
  const print = (title: string, rows: { label: string; value: number }[]) => printReport({ title, subtitle: `Period: ${period}`, columns: [{key:"label",label:"Item"},{key:"value",label:"Amount",align:"right"}], rows: rows.map(x=>({label:x.label,value:formatCurrency(x.value)})) });
  const excel = (name: string, heads: string[], rows: (string|number)[][]) => downloadExcel(`${name}-${range.from}-${range.to}`, heads, rows, name);
  const pnlRows = [{label:"Sales Revenue",value:a.totalSales},{label:"Cost of Goods Sold",value:a.totalCost},{label:"Gross Profit",value:a.grossProfit},{label:"General Expenses",value:a.generalExpenses},{label:"Salaries",value:a.salaries},{label:"Total Operating Expenses",value:a.totalExpenses},{label:"Net Profit / Loss",value:a.netProfit}];

  return <div>
    <PageHeader title="Financial Reports" description="Management reporting for profit, cash and working capital" />
    <div className="mb-6"><RangePicker preset={preset} setPreset={setPreset} custom={custom} setCustom={setCustom} /></div>
    {a.isLoading ? <div className="grid gap-4 sm:grid-cols-3"><Skeleton className="h-28"/><Skeleton className="h-28"/><Skeleton className="h-28"/></div> :
    <Tabs defaultValue="summary"><TabsList className="mb-5 flex h-auto flex-wrap justify-start">
      <TabsTrigger value="summary">Executive Summary</TabsTrigger><TabsTrigger value="pnl">Profit &amp; Loss</TabsTrigger><TabsTrigger value="cash">Cash Flow</TabsTrigger><TabsTrigger value="capital">Working Capital</TabsTrigger><TabsTrigger value="sales">Sales &amp; Receivables</TabsTrigger><TabsTrigger value="purchases">Purchases &amp; Payables</TabsTrigger><TabsTrigger value="inventory">Inventory Position</TabsTrigger><TabsTrigger value="expenses">Expenses</TabsTrigger><TabsTrigger value="analytics">Analytics</TabsTrigger>
    </TabsList>

    <TabsContent value="summary" className="space-y-6">
      <SectionTitle title={`Selected Period · ${period}`} subtitle="Performance figures follow the selected date range." />
      <Kpis items={[["Invoiced Sales",a.totalSales],["COGS",a.totalCost],["Gross Profit",a.grossProfit],["Operating Expenses",a.totalExpenses],["Net Profit / Loss",a.netProfit],["Customer Cash Received",a.customerCashReceived]]}/>
      <SectionTitle title="Current — All Time · As of Today" subtitle="These current balances do not change with the report date range." />
      <Kpis items={[["Current Cash on Hand",a.currentCashOnHand],["Customer Receivables",a.outstanding],["Inventory at Cost",a.inventoryAtCost],["Supplier Payables",a.supplierPayables],["Net Working Capital",a.netWorkingCapital]]}/>
      <Card><CardHeader><CardTitle>Profit Generated vs Cash Position</CardTitle></CardHeader><CardContent><ReportTable heads={["Measure","Basis","Amount"]}>{[["Net Profit Generated","Selected period",a.netProfit],["Customer Cash Received","Selected period",a.customerCashReceived],["Current Customer Receivables","All time",a.outstanding],["Current Cash on Hand","As of today",a.currentCashOnHand],["Current Inventory at Cost","As of today",a.inventoryAtCost],["Current Supplier Payables","All time",a.supplierPayables]].map((x:any)=><TableRow key={x[0]}><TableCell>{x[0]}</TableCell><TableCell className="text-muted-foreground">{x[1]}</TableCell><TableCell className="text-right font-medium">{formatCurrency(x[2])}</TableCell></TableRow>)}</ReportTable><p className="mt-4 rounded-md bg-muted p-3 text-sm text-muted-foreground">Profit and cash are different. Profit measures business performance, while cash, receivables and inventory show where business funds are currently held.</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Where Business Funds Are Currently Tied Up</CardTitle></CardHeader><CardContent className="space-y-4">{[["Cash on Hand",a.currentCashOnHand],["Customer Receivables",a.outstanding],["Inventory at Cost",a.inventoryAtCost]].map(([name,value]:any)=>{const share=grossAssets>0?Math.max(value,0)/grossAssets*100:0; return <div key={name}><div className="mb-1 flex justify-between text-sm"><span>{name}</span><span>{formatCurrency(value)} · {pct(share)}</span></div><div className="h-2 rounded bg-muted"><div className="h-2 rounded bg-primary" style={{width:`${Math.min(share,100)}%`}}/></div></div>})}<p className="border-t pt-3 text-sm">Supplier Payables (liability): <b>{formatCurrency(a.supplierPayables)}</b></p></CardContent></Card>
      <Card><CardHeader><CardTitle>Profit &amp; Collection Indicators</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-4"><Metric label="Gross Margin" value={pct(a.margin)}/><Metric label="Net Margin" value={pct(netMargin)}/><Metric label="Current Receivables" value={formatCurrency(a.outstanding)}/><Metric label="Inventory Capital" value={formatCurrency(a.inventoryAtCost)}/></div></CardContent></Card>
    </TabsContent>

    <TabsContent value="pnl"><Actions onPrint={()=>print("Profit & Loss",pnlRows)} onExcel={()=>excel("profit-and-loss",["Line item","Amount"],pnlRows.map(x=>[x.label,x.value]))}/><Statement title="Profit & Loss" subtitle={`Period: ${period}`} rows={pnlRows} strong={["Gross Profit","Total Operating Expenses","Net Profit / Loss"]}/><p className="mt-3 text-right text-sm font-medium">Net Profit Margin: {a.totalSales ? pct(netMargin) : "N/A"}</p></TabsContent>

    <TabsContent value="cash" className="space-y-5"><Actions onPrint={()=>print("Cash Flow",[{label:"Customer Cash Received",value:a.customerCashReceived},{label:"Vault Top-ups / Capital Added",value:a.topupTotal},{label:"Purchases / Supplier Payments",value:a.periodPurchaseSpend},{label:"Operating Expenses",value:a.totalExpenses},{label:"Net Cash Movement",value:a.netCashMovement},{label:"Current Cash on Hand",value:a.currentCashOnHand}])} onExcel={()=>excel("cash-receipts",["Date","Restaurant","Method","Vault","Amount"],a.payments.map((p:any)=>[p.payment_date,p.restaurants?.name??"Unknown",p.method,p.vault_users?.name??"Missing Vault",Number(p.amount)]))}/>
      <SectionTitle title={`Cash Flow · ${period}`} subtitle="Actual cash movements during the selected period."/><Kpis items={[["Customer Cash Received",a.customerCashReceived],["Top-ups / Capital Added",a.topupTotal],["Purchases / Supplier Payments",a.periodPurchaseSpend],["General Expenses",a.generalExpenses],["Salaries",a.salaries],["Net Cash Movement",a.netCashMovement],["Current Cash on Hand · As of Today",a.currentCashOnHand]]}/>
      <Card><CardHeader><CardTitle>Customer Cash Received by Method</CardTitle></CardHeader><CardContent><ReportTable heads={["Payment Method","Amount"]}>{a.receiptMethods.map((r:any)=><TableRow key={r.name}><TableCell className="capitalize">{r.name}</TableCell><TableCell className="text-right">{formatCurrency(r.value)}</TableCell></TableRow>)}</ReportTable></CardContent></Card>
      <Card><CardHeader><CardTitle>Sales vs Cash Collection</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><Metric label="Period Invoiced Sales" value={formatCurrency(a.totalSales)}/><Metric label="Period Cash Collections" value={formatCurrency(a.customerCashReceived)}/><Metric label="Period Cash Collections / Period Invoiced Sales" value={a.totalSales?pct(a.customerCashReceived/a.totalSales*100):"N/A"}/></div><p className="mt-4 text-sm text-muted-foreground">Cash collected in this period may settle invoices raised in an earlier period; this is not an invoice-by-invoice collection ratio. Current cash is shown separately because the selected range may not begin at the start of financial history.</p></CardContent></Card>
    </TabsContent>

    <TabsContent value="capital"><Actions onPrint={()=>print("Working Capital",[{label:"Current Cash on Hand",value:a.currentCashOnHand},{label:"Customer Receivables",value:a.outstanding},{label:"Inventory at Cost",value:a.inventoryAtCost},{label:"Total Current Assets",value:grossAssets},{label:"Supplier Payables",value:a.supplierPayables},{label:"Net Working Capital",value:a.netWorkingCapital}])} onExcel={()=>excel("working-capital",["Line item","Amount"],[["Current Cash on Hand",a.currentCashOnHand],["Customer Receivables",a.outstanding],["Inventory at Cost",a.inventoryAtCost],["Supplier Payables",a.supplierPayables],["Net Working Capital",a.netWorkingCapital]])}/><Statement title="Business Position — As of Today" subtitle="Current balances · All time (not affected by selected dates)" rows={[{label:"Current Cash on Hand",value:a.currentCashOnHand},{label:"Customer Receivables",value:a.outstanding},{label:"Inventory at Cost",value:a.inventoryAtCost},{label:"Total Current Assets",value:grossAssets},{label:"Less: Supplier Payables",value:a.supplierPayables},{label:"Net Working Capital",value:a.netWorkingCapital}]} strong={["Total Current Assets","Net Working Capital"]}/></TabsContent>

    <TabsContent value="sales" className="space-y-5"><Actions onPrint={()=>print("Sales",[{label:"Period Invoiced Sales",value:a.totalSales},{label:"Current Receivables",value:a.outstanding}])} onExcel={()=>excel("sales",["Date","Invoice","Restaurant","Invoiced","Received","Outstanding"],a.sales.map((s:any)=>[s.sale_date,s.invoice_no,s.restaurants?.name??"Unknown",Number(s.grand_total),Number(s.amount_received),Math.max(Number(s.grand_total)-Number(s.amount_received),0)]))}/><SectionTitle title={`Sales Transactions · ${period}`} subtitle="Sales follow the selected period."/><SalesTable rows={a.sales}/><SectionTitle title="Restaurant Receivables · Current — All Time" subtitle={`Total current receivables: ${formatCurrency(a.outstanding)}`}/><ReportTable heads={["Restaurant","Lifetime Sales","Lifetime Received","Current Outstanding"]}>{a.restaurantReceivables.map((r:any)=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell className="text-right">{formatCurrency(r.sales)}</TableCell><TableCell className="text-right">{formatCurrency(r.received)}</TableCell><TableCell className="text-right font-medium">{formatCurrency(r.outstanding)}</TableCell></TableRow>)}</ReportTable></TabsContent>

    <TabsContent value="purchases" className="space-y-5"><Actions onPrint={()=>print("Purchases & Payables",[{label:"Period Purchases",value:a.totalPurchases},{label:"Current Supplier Payables",value:a.supplierPayables}])} onExcel={()=>excel("purchases",["Date","Reference","Supplier","Total","Paid","Outstanding"],a.purchases.map((p:any)=>[p.purchase_date,p.reference_no,p.suppliers?.name??"Unknown",Number(p.grand_total),Number(p.amount_paid),Math.max(Number(p.grand_total)-Number(p.amount_paid),0)]))}/><SectionTitle title={`Purchase Transactions · ${period}`} subtitle="Purchases follow the selected period."/><PurchaseTable rows={a.purchases}/><SectionTitle title="Supplier Payables · Current — All Time" subtitle={`Total current payables: ${formatCurrency(a.supplierPayables)}`}/><ReportTable heads={["Supplier","Lifetime Purchases","Paid","Current Payable"]}>{a.supplierPayableSummary.map((r:any)=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell className="text-right">{formatCurrency(r.purchases)}</TableCell><TableCell className="text-right">{formatCurrency(r.paid)}</TableCell><TableCell className="text-right font-medium">{formatCurrency(r.outstanding)}</TableCell></TableRow>)}</ReportTable></TabsContent>

    <TabsContent value="inventory" className="space-y-5"><Actions onPrint={()=>print("Inventory Position",[{label:"Current Inventory at Cost",value:a.inventoryAtCost}])} onExcel={()=>excel("inventory",["Product","Category","Current Qty","Avg Cost","Inventory Value","Reorder Level","Status"],a.inventory.map((p:any)=>[p.name,p.categories?.name??"Uncategorized",Number(p.current_stock),Number(p.avg_cost),p.inventoryValue,Number(p.reorder_level),Number(p.current_stock)<=0?"Out of stock":Number(p.current_stock)<=Number(p.reorder_level)?"Low stock":"In stock"]))}/><SectionTitle title="Current Inventory at Cost — As of Today" subtitle="Current position; it is not affected by the selected report dates."/><Kpis items={[["Total Inventory at Cost",a.inventoryAtCost],["Number of Products",a.inventory.length],["Low Stock Products",a.inventory.filter((p:any)=>Number(p.current_stock)>0&&Number(p.current_stock)<=Number(p.reorder_level)).length],["Out of Stock Products",a.inventory.filter((p:any)=>Number(p.current_stock)<=0).length]]}/><p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">Historical inventory valuation as of a previous date is not included in this report version.</p><ReportTable heads={["Product","Category","Current Qty","Avg Cost","Inventory Value","Reorder Level","Status"]}>{a.inventory.map((p:any)=>{const s=Number(p.current_stock)<=0?"Out of stock":Number(p.current_stock)<=Number(p.reorder_level)?"Low stock":"In stock"; return <TableRow key={p.id}><TableCell>{p.name}</TableCell><TableCell>{p.categories?.name??"Uncategorized"}</TableCell><TableCell className="text-right">{p.current_stock}</TableCell><TableCell className="text-right">{formatCurrency(p.avg_cost)}</TableCell><TableCell className="text-right">{formatCurrency(p.inventoryValue)}</TableCell><TableCell className="text-right">{p.reorder_level}</TableCell><TableCell><Badge variant={s==="In stock"?"secondary":"destructive"}>{s}</Badge></TableCell></TableRow>})}</ReportTable><Card><CardHeader><CardTitle>Inventory Cost by Category</CardTitle></CardHeader><CardContent><ReportTable heads={["Category","Inventory Cost"]}>{a.inventoryByCategory.map((r:any)=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell className="text-right">{formatCurrency(r.value)}</TableCell></TableRow>)}</ReportTable></CardContent></Card></TabsContent>

    <TabsContent value="expenses" className="space-y-5"><Actions onPrint={()=>print("Expenses",[{label:"General Expenses",value:a.generalExpenses},{label:"Salaries",value:a.salaries},{label:"Total Operating Expenses",value:a.totalExpenses}])} onExcel={()=>excel("expenses",["Date","Type","Category / Employee","Description","Paid From Vault","Amount"],a.expenses.map((e:any)=>[e.expense_date,e.type,e.expense_categories?.name??e.employees?.name??"-",e.description??"-",e.vault_users?.name??"Missing Vault",Number(e.amount)]))}/><Kpis items={[["General Expenses",a.generalExpenses],["Salaries",a.salaries],["Total Operating Expenses",a.totalExpenses]]}/><ReportTable heads={["Date","Type","Category / Employee","Description","Paid From Vault","Amount"]}>{a.expenses.map((e:any)=><TableRow key={e.id}><TableCell>{formatDate(e.expense_date)}</TableCell><TableCell className="capitalize">{e.type}</TableCell><TableCell>{e.expense_categories?.name??e.employees?.name??"-"}</TableCell><TableCell>{e.description??"-"}</TableCell><TableCell>{e.vault_users?.name??"Missing Vault"}</TableCell><TableCell className="text-right">{formatCurrency(e.amount)}</TableCell></TableRow>)}</ReportTable><Card><CardHeader><CardTitle>Expense Category Totals</CardTitle></CardHeader><CardContent><ReportTable heads={["Category","Amount"]}>{a.expenseCategories.map((r:any)=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell className="text-right">{formatCurrency(r.value)}</TableCell></TableRow>)}</ReportTable></CardContent></Card></TabsContent>

    <TabsContent value="analytics" className="space-y-4"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Revenue by Category</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer><PieChart><Pie data={a.byCategory} dataKey="revenue" nameKey="name" outerRadius={90}>{a.byCategory.map((_:any,i:number)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={(v:number)=>formatCurrency(v)}/></PieChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Profit by Category</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer><BarChart data={a.byCategory}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip formatter={(v:number)=>formatCurrency(v)}/><Bar dataKey="profit" fill="var(--chart-3)"/></BarChart></ResponsiveContainer></CardContent></Card></div><Card><CardHeader><CardTitle>Sales by Restaurant</CardTitle></CardHeader><CardContent><ReportTable heads={["Restaurant","Orders","Sales","Profit"]}>{a.byRestaurant.map((r:any)=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell className="text-right">{r.orders}</TableCell><TableCell className="text-right">{formatCurrency(r.sales)}</TableCell><TableCell className="text-right">{formatCurrency(r.profit)}</TableCell></TableRow>)}</ReportTable></CardContent></Card></TabsContent>
    </Tabs>}
  </div>;
}

function Actions({onPrint,onExcel}:{onPrint:()=>void;onExcel:()=>void}) { return <div className="mb-4 flex justify-end gap-2"><Button variant="outline" size="sm" onClick={onExcel}><FileSpreadsheet className="mr-1 h-4 w-4"/>Excel / CSV</Button><Button variant="outline" size="sm" onClick={onPrint}><Printer className="mr-1 h-4 w-4"/>PDF / Print</Button></div> }
function SectionTitle({title,subtitle}:{title:string;subtitle:string}) { return <div><h2 className="text-lg font-semibold">{title}</h2><p className="text-sm text-muted-foreground">{subtitle}</p></div> }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div> }
function Kpis({items}:{items:(readonly [string,number])[]}) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([name,value])=><Card key={name}><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{name}</p><p className={`mt-1 text-2xl font-bold ${name.includes("Profit")||name.includes("Movement")||name.includes("Working")?(value<0?"text-destructive":"text-success"):""}`}>{typeof value === "number" && (name.includes("Products")||name==="Number of Products") ? value : formatCurrency(value)}</p></CardContent></Card>)}</div> }
function Statement({title,subtitle,rows,strong}:{title:string;subtitle:string;rows:{label:string;value:number}[];strong:string[]}) { return <Card><CardHeader><CardTitle>{title}</CardTitle><p className="text-sm text-muted-foreground">{subtitle}</p></CardHeader><CardContent><Table><TableBody>{rows.map(r=><TableRow key={r.label} className={strong.includes(r.label)?"border-y-2 bg-muted/40 text-base font-bold":""}><TableCell>{r.label}</TableCell><TableCell className={`${r.label==="Net Profit / Loss"?(r.value<0?"text-destructive":"text-success"):""} text-right`}>{formatCurrency(r.value)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card> }
function SalesTable({rows}:{rows:any[]}) { return <ReportTable heads={["Date","Invoice","Restaurant","Invoiced Amount","Amount Received","Outstanding","Status"]}>{rows.map(s=>{const due=Math.max(Number(s.grand_total)-Number(s.amount_received),0);return <TableRow key={s.id}><TableCell>{formatDate(s.sale_date)}</TableCell><TableCell>{s.invoice_no}</TableCell><TableCell>{s.restaurants?.name??"Unknown"}</TableCell><TableCell className="text-right">{formatCurrency(s.grand_total)}</TableCell><TableCell className="text-right">{formatCurrency(s.amount_received)}</TableCell><TableCell className="text-right">{formatCurrency(due)}</TableCell><TableCell><Badge variant={due?"destructive":"secondary"}>{status(due)}</Badge></TableCell></TableRow>})}</ReportTable> }
function PurchaseTable({rows}:{rows:any[]}) { return <ReportTable heads={["Date","Reference","Supplier","Purchase Total","Amount Paid","Outstanding","Status"]}>{rows.map(p=>{const due=Math.max(Number(p.grand_total)-Number(p.amount_paid),0);return <TableRow key={p.id}><TableCell>{formatDate(p.purchase_date)}</TableCell><TableCell>{p.reference_no}</TableCell><TableCell>{p.suppliers?.name??"Unknown"}</TableCell><TableCell className="text-right">{formatCurrency(p.grand_total)}</TableCell><TableCell className="text-right">{formatCurrency(p.amount_paid)}</TableCell><TableCell className="text-right">{formatCurrency(due)}</TableCell><TableCell><Badge variant={due?"destructive":"secondary"}>{status(due)}</Badge></TableCell></TableRow>})}</ReportTable> }
function ReportTable({heads,children}:{heads:string[];children:React.ReactNode}) { return <div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow>{heads.map((h,i)=><TableHead key={h} className={i>=heads.length-3?"text-right":""}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></div> }
