import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRightLeft, Eye, FileSpreadsheet, HandCoins, Plus, Printer, Power } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { PageHeader } from "@/components/app/PageHeader";
import { ConfirmDialog } from "@/components/app/ConfirmDialog";
import { formatCurrency, formatDate } from "@/lib/format";
import { printReport } from "@/lib/print";
import { downloadExcel } from "@/lib/xlsx";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/_authenticated/vault")({ component: VaultPage });
const today = () => new Date().toISOString().slice(0, 10);
const labelType = (type: string) => type === "owner_cash" ? "Owner Cash" : "Business Cash";

function VaultPage() {
  const qc = useQueryClient();
  const [addOpen, setAddOpen] = useState(false);
  const [topOpen, setTopOpen] = useState<any>(null);
  const [movementOpen, setMovementOpen] = useState(false);
  const [toggleUser, setToggleUser] = useState<any>(null);
  const [voidMovement, setVoidMovement] = useState<any>(null);
  const [voidReason, setVoidReason] = useState("");
  const [form, setForm] = useState({ name: "", phone: "", notes: "", opening_balance: 0, vault_type: "business_cash" });
  const [top, setTop] = useState({ amount: 0, topup_date: today(), note: "" });
  const [movement, setMovement] = useState({ movement_type: "internal_transfer", source: "", destination: "", amount: 0, movement_date: today(), note: "" });

  const get = (key: string, table: string, select = "*") => useQuery({ queryKey: [key], queryFn: async () => { const { data, error } = await (supabase.from(table as any) as any).select(select); if (error) throw error; return (data ?? []) as any[]; } });
  const { data: users, isLoading } = get("vault_users", "vault_users");
  const { data: topups } = get("vault_topups", "vault_topups");
  const { data: purchases } = get("vault_purchases_all", "purchases", "id,vault_user_id,amount_paid");
  const { data: expenses } = get("vault_expenses_all", "expenses", "id,vault_user_id,amount");
  const { data: receipts } = get("vault_customer_payments_all", "payments", "id,vault_user_id,amount");
  const { data: supplierPayments } = get("vault_supplier_payments_all", "supplier_payments", "id,vault_user_id,amount,purchase_id");
  const { data: movements } = useQuery({ queryKey: ["vault_cash_movements"], queryFn: async () => { const { data, error } = await (supabase.from("vault_cash_movements" as any) as any).select("*").order("movement_date", { ascending: false }).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as any[]; } });

  const splitIds = useMemo(() => { const map = new Map<string, Set<string>>(); for (const x of supplierPayments ?? []) if (x.purchase_id && x.vault_user_id) { if (!map.has(x.purchase_id)) map.set(x.purchase_id, new Set()); map.get(x.purchase_id)!.add(x.vault_user_id); } return new Set([...map].filter(([, ids]) => ids.size > 1).map(([id]) => id)); }, [supplierPayments]);
  const sums = (id: string) => {
    const topup = (topups ?? []).filter(x => x.vault_user_id === id).reduce((n,x)=>n+Number(x.amount),0);
    const received = (receipts ?? []).filter(x => x.vault_user_id === id).reduce((n,x)=>n+Number(x.amount),0);
    const purchase = (purchases ?? []).filter(x => x.vault_user_id === id && !splitIds.has(x.id)).reduce((n,x)=>n+Number(x.amount_paid),0);
    const split = (supplierPayments ?? []).filter(x => x.vault_user_id === id && x.purchase_id && splitIds.has(x.purchase_id)).reduce((n,x)=>n+Number(x.amount),0);
    const expense = (expenses ?? []).filter(x => x.vault_user_id === id).reduce((n,x)=>n+Number(x.amount),0);
    const cashIn = (movements ?? []).filter(x => !x.voided_at && x.destination_vault_user_id === id).reduce((n,x)=>n+Number(x.amount),0);
    const cashOut = (movements ?? []).filter(x => !x.voided_at && x.source_vault_user_id === id).reduce((n,x)=>n+Number(x.amount),0);
    return { topup, received, spend: purchase + split + expense, cashIn, cashOut };
  };
  const rows = (users ?? []).map(u => { const s=sums(u.id); return { ...u, ...s, balance:Number(u.opening_balance)+s.topup+s.received+s.cashIn-s.cashOut-s.spend }; });
  const businessCash = rows.filter(x=>x.vault_type!=="owner_cash").reduce((n,x)=>n+x.balance,0);
  const ownerCash = rows.filter(x=>x.vault_type==="owner_cash").reduce((n,x)=>n+x.balance,0);
  const ownerDistributions = (movements ?? []).filter(x=>!x.voided_at && x.movement_type==="owner_distribution").reduce((n,x)=>n+Number(x.amount),0);
  const totalReceipts = rows.reduce((n,x)=>n+x.received,0), totalSpent=rows.reduce((n,x)=>n+x.spend,0);
  const activeBusiness = rows.filter(x=>x.is_active && x.vault_type!=="owner_cash"), activeOwners=rows.filter(x=>x.is_active && x.vault_type==="owner_cash");
  const source = rows.find(x=>x.id===movement.source);
  const destinations = movement.movement_type === "owner_distribution" ? activeOwners : activeBusiness.filter(x=>x.id!==movement.source);
  const nameFor = (id:string) => rows.find(x=>x.id===id)?.name ?? "Unknown";

  const refresh = () => qc.invalidateQueries();
  const addUser = useMutation({ mutationFn: async()=>{if(!form.name.trim())throw Error("Enter a name"); const {error}=await (supabase.from("vault_users" as any) as any).insert({...form,name:form.name.trim()});if(error)throw error;},onSuccess:()=>{refresh();setAddOpen(false);setForm({name:"",phone:"",notes:"",opening_balance:0,vault_type:"business_cash"});toast.success("Vault user created");},onError:(e:Error)=>toast.error(e.message)});
  const addTopup = useMutation({ mutationFn:async()=>{if(!topOpen||topOpen.vault_type==="owner_cash")throw Error("External funding can only be added to Business Cash");if(top.amount<=0)throw Error("Enter an amount");const {data:u}=await supabase.auth.getUser();const {error}=await (supabase.from("vault_topups" as any) as any).insert({vault_user_id:topOpen.id,amount:top.amount,topup_date:top.topup_date,note:top.note||null,created_by:u.user?.id});if(error)throw error;},onSuccess:()=>{refresh();setTopOpen(null);toast.success("External capital added");},onError:(e:Error)=>toast.error(e.message)});
  const recordMovement = useMutation({ mutationFn:async()=>{if(!movement.source||!movement.destination)throw Error("Select source and destination");if(movement.amount<=0)throw Error("Enter an amount");const {error}=await (supabase.rpc as any)("record_vault_cash_movement",{p_movement_type:movement.movement_type,p_source_vault_user_id:movement.source,p_destination_vault_user_id:movement.destination,p_amount:movement.amount,p_movement_date:movement.movement_date,p_note:movement.note||null});if(error)throw error;},onSuccess:()=>{refresh();setMovementOpen(false);setMovement({...movement,source:"",destination:"",amount:0,note:""});toast.success("Cash movement recorded");},onError:(e:Error)=>toast.error(e.message)});
  const toggle = useMutation({mutationFn:async(u:any)=>{const {error}=await (supabase.from("vault_users" as any) as any).update({is_active:!u.is_active}).eq("id",u.id);if(error)throw error;},onSuccess:()=>{refresh();setToggleUser(null);toast.success("Vault status updated");},onError:(e:Error)=>toast.error(e.message)});
  const voidIt = useMutation({mutationFn:async()=>{if(!voidReason.trim())throw Error("Void reason is required");const {error}=await (supabase.rpc as any)("void_vault_cash_movement",{p_movement_id:voidMovement.id,p_reason:voidReason});if(error)throw error;},onSuccess:()=>{refresh();setVoidMovement(null);setVoidReason("");toast.success("Movement voided");},onError:(e:Error)=>toast.error(e.message)});
  const openMovement = () => { const rotator=activeBusiness.find(x=>x.name.trim().toLowerCase()==="profit or rotator vault");setMovement({...movement,source:rotator?.id??activeBusiness[0]?.id??"",destination:""});setMovementOpen(true); };

  const exportRows=rows.map(x=>[x.name,labelType(x.vault_type),x.opening_balance,x.topup,x.received,x.cashIn,x.cashOut,x.spend,x.balance]);
  const exportExcel=()=>downloadExcel(`vault-users-${today()}`,["Name","Vault Type","Opening","External Top-ups","Receipts","Cash Movement In","Cash Movement Out","Business Spend","Balance"],exportRows,"Vault Users");
  const printAll=()=>printReport({title:"Vault Cash Report",subtitle:`Generated ${formatDate(today())}`,columns:[{key:"name",label:"Name"},{key:"type",label:"Vault Type"},{key:"in",label:"Movement In",align:"right"},{key:"out",label:"Movement Out",align:"right"},{key:"balance",label:"Balance",align:"right"}],rows:rows.map(x=>({name:x.name,type:labelType(x.vault_type),in:formatCurrency(x.cashIn),out:formatCurrency(x.cashOut),balance:formatCurrency(x.balance)})),summary:[{label:"Business Cash on Hand",value:formatCurrency(businessCash)},{label:"Owner Cash / Distributed",value:formatCurrency(ownerCash)},{label:"Owner Distributions",value:formatCurrency(ownerDistributions)}]});

  return <div><PageHeader title="Vault Users" description="Auditable business cash custody and owner distribution wallets" actions={<div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={exportExcel}><FileSpreadsheet className="mr-1 h-4 w-4"/>Excel</Button><Button variant="outline" size="sm" onClick={printAll}><Printer className="mr-1 h-4 w-4"/>PDF</Button><Button size="sm" variant="secondary" onClick={openMovement}><ArrowRightLeft className="mr-1 h-4 w-4"/>Cash Movement</Button><Button size="sm" onClick={()=>setAddOpen(true)}><Plus className="mr-1 h-4 w-4"/>Add Vault User</Button></div>}/>
  <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Business Cash on Hand",businessCash],["Owner Cash / Distributed",ownerCash],["Owner Distributions",ownerDistributions],["Restaurant Receipts",totalReceipts],["Spent via Vault",totalSpent]].map(([l,v])=><Card key={String(l)}><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{l}</p><p className="mt-1 text-xl font-bold">{formatCurrency(Number(v))}</p></CardContent></Card>)}</div>
  <Card className="p-4">{isLoading?<Skeleton className="h-32"/>:<Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead className="text-right">Opening</TableHead><TableHead className="text-right">Top-ups</TableHead><TableHead className="text-right">Receipts</TableHead><TableHead className="text-right">Cash In</TableHead><TableHead className="text-right">Cash Out</TableHead><TableHead className="text-right">Business Spend</TableHead><TableHead className="text-right">Balance</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map(x=><TableRow key={x.id} className={!x.is_active?"opacity-60":""}><TableCell className="font-medium">{x.name}</TableCell><TableCell><Badge variant={x.vault_type==="owner_cash"?"outline":"secondary"}>{labelType(x.vault_type)}</Badge></TableCell>{[x.opening_balance,x.topup,x.received,x.cashIn,x.cashOut,x.spend,x.balance].map((v,i)=><TableCell key={i} className="text-right">{formatCurrency(v)}</TableCell>)}<TableCell className="whitespace-nowrap">{x.vault_type!=="owner_cash"&&x.is_active&&<Button variant="ghost" size="icon" title="External Top-up / Capital Added" onClick={()=>setTopOpen(x)}><HandCoins className="h-4 w-4"/></Button>}<Button variant="ghost" size="icon" asChild><Link to="/vault/$id" params={{id:x.id}}><Eye className="h-4 w-4"/></Link></Button><Button variant="ghost" size="icon" title={x.is_active?"Deactivate":"Reactivate"} onClick={()=>setToggleUser(x)}><Power className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table>}</Card>
  <h2 className="mb-3 mt-8 text-xl font-semibold">Cash Movement History</h2><Card className="p-4"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Type</TableHead><TableHead>From</TableHead><TableHead>To</TableHead><TableHead className="text-right">Amount</TableHead><TableHead>Note</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{(movements??[]).map(x=><TableRow key={x.id}><TableCell>{formatDate(x.movement_date)}</TableCell><TableCell>{x.movement_type==="owner_distribution"?"Owner Distribution":"Internal Transfer"}</TableCell><TableCell>{nameFor(x.source_vault_user_id)}</TableCell><TableCell>{nameFor(x.destination_vault_user_id)}</TableCell><TableCell className="text-right">{formatCurrency(x.amount)}</TableCell><TableCell>{x.note??"-"}</TableCell><TableCell><Badge variant={x.voided_at?"destructive":"secondary"}>{x.voided_at?"Voided":"Active"}</Badge>{x.void_reason&&<div className="text-xs text-muted-foreground">{x.void_reason}</div>}</TableCell><TableCell>{!x.voided_at&&<Button variant="outline" size="sm" onClick={()=>setVoidMovement(x)}>Void</Button>}</TableCell></TableRow>)}</TableBody></Table></Card>
  <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>New Vault User</DialogTitle></DialogHeader><div className="space-y-3"><Label>Name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Label>Vault Type</Label><Select value={form.vault_type} onValueChange={v=>setForm({...form,vault_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="business_cash">Business Cash</SelectItem><SelectItem value="owner_cash">Owner Cash / Distribution Wallet</SelectItem></SelectContent></Select><p className="text-xs text-muted-foreground">{form.vault_type==="business_cash"?"Company cash that is still part of FH Traders.":"Cash distributed outside the business to an owner. This is not an expense category."}</p><Label>Phone</Label><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Label>Opening Balance</Label><Input type="number" value={form.opening_balance} onChange={e=>setForm({...form,opening_balance:+e.target.value})}/><Label>Notes</Label><Input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><DialogFooter><Button onClick={()=>addUser.mutate()}>Save</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!topOpen} onOpenChange={v=>!v&&setTopOpen(null)}><DialogContent><DialogHeader><DialogTitle>External Top-up / Capital Added</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">For money moved from another FH Traders Vault, use Cash Movement instead.</p><Label>Amount</Label><Input type="number" value={top.amount} onChange={e=>setTop({...top,amount:+e.target.value})}/><Label>Date</Label><Input type="date" value={top.topup_date} onChange={e=>setTop({...top,topup_date:e.target.value})}/><Label>Note</Label><Input value={top.note} onChange={e=>setTop({...top,note:e.target.value})}/><DialogFooter><Button onClick={()=>addTopup.mutate()}>Save</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={movementOpen} onOpenChange={setMovementOpen}><DialogContent><DialogHeader><DialogTitle>Transfer / Distribute Funds</DialogTitle></DialogHeader><Label>Movement Type</Label><Select value={movement.movement_type} onValueChange={v=>setMovement({...movement,movement_type:v,destination:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="internal_transfer">Internal Vault Transfer</SelectItem><SelectItem value="owner_distribution">Owner Distribution / Drawings</SelectItem></SelectContent></Select><Label>Source Vault</Label><Select value={movement.source} onValueChange={v=>setMovement({...movement,source:v,destination:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{activeBusiness.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select>{source&&<p className="rounded bg-muted p-2 text-sm">Available balance: <strong>{formatCurrency(source.balance)}</strong></p>}<Label>Destination</Label><Select value={movement.destination} onValueChange={v=>setMovement({...movement,destination:v})}><SelectTrigger><SelectValue placeholder="Select destination"/></SelectTrigger><SelectContent>{destinations.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select><Label>Amount</Label><Input type="number" value={movement.amount} onChange={e=>setMovement({...movement,amount:+e.target.value})}/><Label>Date</Label><Input type="date" value={movement.movement_date} onChange={e=>setMovement({...movement,movement_date:e.target.value})}/><Label>Note</Label><Textarea value={movement.note} onChange={e=>setMovement({...movement,note:e.target.value})}/><DialogFooter><Button disabled={recordMovement.isPending} onClick={()=>recordMovement.mutate()}>Record Movement</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!voidMovement} onOpenChange={v=>!v&&setVoidMovement(null)}><DialogContent><DialogHeader><DialogTitle>Void Cash Movement</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">The entry remains auditable but will stop affecting balances and reports. Re-enter a corrected movement separately.</p><Label>Reason (required)</Label><Textarea value={voidReason} onChange={e=>setVoidReason(e.target.value)}/><DialogFooter><Button variant="destructive" onClick={()=>voidIt.mutate()}>Void Movement</Button></DialogFooter></DialogContent></Dialog>
  <ConfirmDialog open={!!toggleUser} onOpenChange={v=>!v&&setToggleUser(null)} title={`${toggleUser?.is_active?"Deactivate":"Reactivate"} ${toggleUser?.name}?`} description="Historical records and ledger references will remain intact." onConfirm={()=>toggleUser&&toggle.mutate(toggleUser)}/>
  </div>;
}
