/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRestaurantsRouteImport } from './routes/_authenticated/restaurants'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedRestaurantsIdRouteImport } from './routes/_authenticated/restaurants.$id'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRestaurantsRoute =
  AuthenticatedRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestaurantsIdRoute =
  AuthenticatedRestaurantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRestaurantsRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/restaurants': typeof AuthenticatedRestaurantsRouteWithChildren
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/restaurants': typeof AuthenticatedRestaurantsRouteWithChildren
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/_authenticated/restaurants': typeof AuthenticatedRestaurantsRouteWithChildren
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/restaurants/$id': typeof AuthenticatedRestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/products'
    | '/purchases'
    | '/restaurants'
    | '/purchases/new'
    | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/products'
    | '/purchases'
    | '/restaurants'
    | '/purchases/new'
    | '/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/categories'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/restaurants'
    | '/_authenticated/purchases/new'
    | '/_authenticated/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/restaurants': {
      id: '/_authenticated/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof AuthenticatedRestaurantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurants/$id': {
      id: '/_authenticated/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedRestaurantsRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
  }
}

interface AuthenticatedPurchasesRouteChildren {
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
}

const AuthenticatedPurchasesRouteChildren: AuthenticatedPurchasesRouteChildren =
  {
    AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  }

const AuthenticatedPurchasesRouteWithChildren =
  AuthenticatedPurchasesRoute._addFileChildren(
    AuthenticatedPurchasesRouteChildren,
  )

interface AuthenticatedRestaurantsRouteChildren {
  AuthenticatedRestaurantsIdRoute: typeof AuthenticatedRestaurantsIdRoute
}

const AuthenticatedRestaurantsRouteChildren: AuthenticatedRestaurantsRouteChildren =
  {
    AuthenticatedRestaurantsIdRoute: AuthenticatedRestaurantsIdRoute,
  }

const AuthenticatedRestaurantsRouteWithChildren =
  AuthenticatedRestaurantsRoute._addFileChildren(
    AuthenticatedRestaurantsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRouteWithChildren
  AuthenticatedRestaurantsRoute: typeof AuthenticatedRestaurantsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRouteWithChildren,
  AuthenticatedRestaurantsRoute: AuthenticatedRestaurantsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
